### ISSUE TITLE
Hint コンポーネントをつくる

### ISSUE THREAD

**Issue by chvmvd** [ut-code/utcode-learn#175]
ヒントを答えのように、折りたたみにしたいという話があった。
答えは Answer コンポーネントがあるが、ヒントに関しては作っていない。

とりあえず、「解答」を「ヒント」に書き換えれば良さそう。
https://github.com/ut-code/utcode-learn/blob/master/src/components/Answer/index.jsx

**Comment by kazukinumazato** [comment]
Dropdownコンポーネントを作って属性をanswerかhintで切り替えられるようにしてはどうでしょう？

**Comment by kazukinumazato** [comment]
DropdownというよりはCollapseBarか

**Comment by chvmvd** [comment]
うーん。
あまり良いイメージが湧きません。
Accordion 的にすると、今と変わらないし…

**Comment by naka-12** [comment]
Accordion だとダメなんでしたっけ
（ヒントと解答で折りたたみのギミックを変えたいみたいな話ですか？）

**Comment by chvmvd** [comment]
むしろ Accordion が良さそうですね。眠くて、頭回ってなかったみたいです。
Details コンポーネント以外で Docusaurus が用意している似たようなコンポーネントはなさそうです…
Details コンポーネント以外にするなら、ちょっと大変かもです。

**Comment by naka-12** [comment]
なるほど。お疲れ様です。
ヒントも解答も Details コンポーネントで良いと思います！
