### ISSUE TITLE
環境構築のセクション？を作る

### ISSUE THREAD

**Issue by chvmvd** [ut-code/utcode-learn#203]

**Comment by chvmvd** [comment]
昨日の話し合いの結果
- デプロイ方法についてまとめる
- Linter、Formatter の説明を加える。
- CI、CD について書く。
- Docker について書く。
- マイグレーションについて書く。

**Comment by kazukinumazato** [comment]
あとできればクラウドを用いたサーバー構築（AWSなど）についても書きたい

**Comment by chvmvd** [comment]
ほえー

**Comment by chvmvd** [comment]
とりあえず、デプロイ方法と ESLint、Prettier のことをちゃんと書いて、残りはおまけとして書くのが良いかな。
個人的には、CI、CD、Docker を標準にしたいwけど。

**Comment by chvmvd** [comment]
一旦、クローズします。
