### ISSUE TITLE
「Web プログラミングの初歩」について

### ISSUE THREAD

**Issue by chelproc** [ut-code/utcode-learn#276]
https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L84
前置詞を使う変数名は冗長なので避けたほうが良い。`nameLength`

---

https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L104
理由を説明したほうがよさそう

---

https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L122
「以下」は下になにも続かない場合のみにしたほうがいい

---

https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L135
前置詞

---

https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L159
箇条書き入れる、かっこと文章の間にスペース、用語にはバッククォート、他も何か所かある

---

https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L174
個人的には対称性を意識して else を入れる派。linter はちゃんとチェックできるので問題ない

---

https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L202
この行いる？for が実行されないからなくてもよさそう。

---

https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L208
一応 sequence.pop と書ける

---

https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L232
「し」を接続詞として用いるのは口語的に聞こえる
http://goro55.cocolog-nifty.com/japanese/2012/07/post-e5a4.html

---

https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L240
「では」の接続では曖昧。主語なら明示的に「は」を使ったほうがいい。

---

https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L243
どちらかといえば JavaScript 側をバッククォートかシングルクォートにするのが一般的。他もいくつかある。

---

https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L246
拡張子は jpg が一般的

**Comment by chvmvd** [comment]
タスクリストにしていただけると助かります。

**Comment by chvmvd** [comment]
> 前置詞を使う変数名は冗長なので避けたほうが良い。`nameLength`
そうですね！直しました。
Fixed with #281.

**Comment by chvmvd** [comment]
> https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L104
> 理由を説明したほうがよさそう

[こちら](http://localhost:3000/docs/trial-session/boolean/#%E8%AA%B2%E9%A1%8C)で説明しているので、理由は要らないかと思ったのですが、どうでしょう？

**Comment by chvmvd** [comment]
> https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L122
> 「以下」は下になにも続かない場合のみにしたほうがいい

そうですね。直しました。
Fixed with #282.

**Comment by chvmvd** [comment]
> https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L135
> 前置詞

これは、前置詞を抜かすとどのような変数かわかりにくくなってしまうような気がします。
前置詞を使わないと、`aNumber` のようになってしまいわかりにくくなってしまいます…

**Comment by chvmvd** [comment]
> https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L159
> 箇条書き入れる、かっこと文章の間にスペース、用語にはバッククォート、他も何か所かある

直しました。
Fixed with #283.

**Comment by chvmvd** [comment]
> https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L174
> 個人的には対称性を意識して else を入れる派。linter はちゃんとチェックできるので問題ない

これは、僕も else を入れる派です。標準の ESLint はこれに怒りませんが Airbnb の ESLint はこれで怒るらしいので、議論の余地がありそうです。
この Issue は、一旦 #284 に移します。

**Comment by chvmvd** [comment]
> https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L202
> この行いる？for が実行されないからなくてもよさそう。

ごめんなさい。要らないです…
僕が間違えてました…
Fixed with #285.

**Comment by chvmvd** [comment]
> https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L208
> 一応 sequence.pop と書ける

初めて知りました:eyes:
$n=0$ で動かないので、今回はそのままにします。

**Comment by chvmvd** [comment]
> https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L232
> 「し」を接続詞として用いるのは口語的に聞こえる
> http://goro55.cocolog-nifty.com/japanese/2012/07/post-e5a4.html

Fixed with #286.

**Comment by chvmvd** [comment]
> https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L240
> 「では」の接続では曖昧。主語なら明示的に「は」を使ったほうがいい。

Fixed with #287.

**Comment by chvmvd** [comment]
> https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L243
> どちらかといえば JavaScript 側をバッククォートかシングルクォートにするのが一般的。他もいくつかある。

Fixed with #288.

**Comment by chvmvd** [comment]
> https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L246
> 拡張子は jpg が一般的

Fixed with #289.

**Comment by chvmvd** [comment]
> > https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L135
> > 
> > 前置詞
> 
> これは、前置詞を抜かすとどのような変数かわかりにくくなってしまうような気がします。 前置詞を使わないと、`aNumber` のようになってしまいわかりにくくなってしまいます…

人の名前を変えて対応しました。
`tanakaHandTotal` と `satoHandTotal` にしました。

Fixed with #290.

**Comment by chvmvd** [comment]
> > https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L104
> > 
> > 理由を説明したほうがよさそう
> 
> [こちら](http://localhost:3000/docs/trial-session/boolean/#%E8%AA%B2%E9%A1%8C)で説明しているので、理由は要らないかと思ったのですが、どうでしょう？



> > https://github.com/ut-code/utcode-learn/blob/56221e9f2e869a046482c9ae6e27a8e0d0b18575/docs/6-exercise/1-basis-of-web/index.md#L174
> > 
> > 個人的には対称性を意識して else を入れる派。linter はちゃんとチェックできるので問題ない
> 
> これは、僕も else を入れる派です。標準の ESLint はこれに怒りませんが Airbnb の ESLint はこれで怒るらしいので、議論の余地がありそうです。 この Issue は、一旦 #284 に移します。

@chelproc この 2 つ以外は、すべて解決しました。
前者は、とりあえず解決ということにします。
後者は、#284 に移しました。

一旦、この Issue をクローズします。まだ、問題があったら、リオープンしてください。
