### ISSUE TITLE
この教材が自由に使えるものであることを教材自体にも明記した方が良さそう。

### ISSUE THREAD

**Issue by chvmvd** [ut-code/utcode-learn#335]

**Comment by Fridge0** [comment]
教材の最初のページに
"ut.code(); Learn は、東京大学のソフトウェアエンジニアリングコミュニティ ut.code(); の内部向け学習資料です。"
と書いてあるのでこれも消した方がよさそうですね

**Comment by Fridge0** [comment]
プルリク出しました。解決済みとみなします。
