### ISSUE TITLE
｢三項演算子｣から｢条件演算子｣に移行

### ISSUE THREAD

**Issue by Fridge0** [ut-code/utcode-learn#442]
三項演算子は3つのoperandを取る演算子の総称(のはず)。
唯一条件演算子のみが当てはまるため、条件演算子が三項演算子とも呼ばれているけれど、条件演算子の方が的確。

**Comment by chvmvd** [comment]
そんなに単純な問題ではないかも。
個人的には、条件演算子がある程度一般的だったら、MDNに準拠するために変えたい気持ちはある。三項演算子の方が聞くことが多いから、条件演算子がある程度知名度があれば変えたいなという気持ち。

c.f.
MDNは、条件（三項）演算子
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Conditional_operator
サバイバルTypeScriptは、三項演算子
https://typescriptbook.jp/reference/statements/ternary-operator

**Comment by Fridge0** [comment]
条件（三項）演算子がいいですかね？

**Comment by chvmvd** [comment]
ある程度使われているのを確認したら、条件演算子に変えても良いかとは思う。
