### ISSUE TITLE
タイトルメニューのdescription改善

### ISSUE THREAD

**Issue by Fridge0** [ut-code/utcode-learn#446]
not 内部用 anymore

**Comment by Fridge0** [comment]
ut.code(); 公式の学習カリキュラムです。ut.code(); 外部の方でもご利用いただけます。
ut.code(); Learn は、全くの未経験の状態からでも、自力で Web サービスが開発できるようになれるようにするための、ut.code(); 公式の教材です。

**Comment by Fridge0** [comment]
AI案
ut.code(); Learn は、東京大学のソフトウェアエンジニアリングコミュニティである ut.code(); の公式教材です。この教材は、全くの未経験の状態からでも、自力で Web サービスが開発できるようになれるようにするためのものです。﻿
ut.code(); は、非営利の大学のサークルであり、日本のWeb技術の発展をサポートしています。学習カリキュラムをオープンソースで公開しており、初心者からでも実際にサービスを開発できるようにしています。﻿

**Comment by chvmvd** [comment]
めちゃくちゃ良いと思う！

**Comment by Fridge0** [comment]
プルリク出しました。眠いので閉じます
