### ISSUE TITLE
DOCTYPE大文字？小文字？

### ISSUE THREAD

**Issue by Fridge0** [ut-code/utcode-learn#470]
自分のPrettier (v10.1.0) ではDOCTYPEは大文字になります。

**Comment by chvmvd** [comment]
結論としては、最新の`prettier`では、`DOCTYPE`は小文字です。3.0からそうなっています。
cf. https://prettier.io/blog/2023/07/05/3.0.0.html#print-html5-doctype-in-lowercase-7391httpsgithubcomprettierprettierpull7391-by-fiskerhttpsgithubcomfisker

`prettier-vscode`の内部で使われている`prettier`は、`^2.8.8`になっています。
cf. https://github.com/prettier/prettier-vscode/blob/affc1e5b44fc6d0d9d4a957e327e0da57045bf56/package.json#L130
また、Prettier 2では`DOCTYPE`が大文字に、Prettier 3では小文字になります。
そのため、`prettier-vscode`を使うとPrettier 2が動くため小文字になってしまいます。
ちなみに、v10.1.0というのは、おそらく`prettier`というよりは`prettier-vscode`のバージョンのことです。ちなみに、`prettier`の最新は、`3.0.3`になっています。

ということで、バージョンが違うので大変なのですが、どうやら`prettier-vscode`はワークスペース内にPrettierが入っている場合にはそのワークスペースのPrettierを使うという挙動をとるようです。そのため、VS Codeでこのリポジトリのワークスペースを開いていれば正しくPrettier 3を使うことができるはずになっています。

**Comment by chvmvd** [comment]
基本的にVS Codeは、あくまでもエディタの一つなので（VimとかEmacsとかを使っている人のことを考えないといけない。）プロジェクトでは、VS Codeの設定でしばるというよりもCLIでしばることが多いです。そのため、このリポジトリでもわざわざPrettierをnpmでインストールしてそれでバージョンを合わせています。

**Comment by Fridge0** [comment]
utcode-learn内で試したところ小文字になりました！閉じます。
