### ISSUE TITLE
Fetch API の断片を GET/POSTリクエストの解答例の下に追加する

### ISSUE THREAD

**Issue by Fridge0** [ut-code/utcode-learn#521]
テンプレートエンジンがなくなったので、index.htmlとserver.mjsを分離できなくなった。
GETリクエストだけでも fetch API を使いたい (postはフォームでいい)

**Comment by chvmvd** [comment]
FetchAPIを扱う必要性ないと思うのですが、なぜ入れようと思ったのですか？
今のままで良いと思うのですが。

**Comment by chvmvd** [comment]
FetchAPIを後でやるのにそこでわざわざ触れる必要はない気がしますが。

**Comment by Fridge0** [comment]
上に書いたようにindex.htmlとserver.mjsが分離できなくなったからです。

**Comment by Fridge0** [comment]
3章終了時点でサーバーのデータを使うようなwenサイトを作ろうとすると、テンプレートリテラルになってしまいます

**Comment by chvmvd** [comment]
テンプレートリテラルで良いのではないですか？EJSをやめるというのは、テンプレートリテラルにするという理由でそうなったはず。

**Comment by chvmvd** [comment]
そもそもEJSの`index.html`とFetch APIの`index.html`はまったく違うものなので、Fetch APIを導入してもメリットをまったく感じられない気がします。

**Comment by Fridge0** [comment]
それだとブラウザに表示するHTMLとサーバー側のJSが分離できなくなりませんか？

**Comment by Fridge0** [comment]
readFileSyncにテンプレートリテラルは適用できなかったと思いますし

**Comment by Fridge0** [comment]
> そもそもEJSの`index.html`とFetch APIの`index.html`はまったく違うものなので、Fetch APIを導入してもメリットをまったく感じられない気がします。

クライアント <-> サーバー間の通信が減らせてより直感的になるので、EJSよりもいいと思います

**Comment by chvmvd** [comment]
> それだとブラウザに表示するHTMLとサーバー側のJSが分離できなくなりませんか？

それは別に良い気がします。ちゃんとしたものを作りたければ、EJSとかFetch APIを使えば良いわけだし。

**Comment by chvmvd** [comment]
> readFileSyncにテンプレートリテラルは適用できなかったと思いますし

別にインポートしないで、一つのファイルに書けば良いのでは？

**Comment by chvmvd** [comment]
> > そもそもEJSの`index.html`とFetch APIの`index.html`はまったく違うものなので、Fetch APIを導入してもメリットをまったく感じられない気がします。
> 
> 
> 
> クライアント <-> サーバー間の通信が減らせてより直感的になるので、EJSよりもいいと思います

それは、そもそもサーバーをAPIサーバーとしてだけ教えれば良いということになると思いますが、それだと全ての章を書き換えないといけないですね。
一方で、テンプレートエンジンを使った方法はかなり一般的なので教える価値はあると思います。そもそも、こちらの方を最初に、知るべきな気もするし。

**Comment by Fridge0** [comment]
テンプレートエンジンは｢サーバーはリクエストに対してつねに 直接解釈可能なテキスト を送信するものである｣という思想の中で、フォーマットなどを使って無理やりファイルを分離しようとしたからああいう記法になったと思ってて、それに対して Fetch API はクライアント・サーバー間のデータの直接的な通信を認めることでかなりネイティブな書き方ができるようになったものだと思ってます。

なので、現代の開発事情は知りませんが、テンプレートエンジンを教える必要は必ずしもないのでは...?

**Comment by chvmvd** [comment]
たしかに、テンプレートエンジン自体は下火になりはしましたが、今でもSSRなどでテンプレートエンジンは使われているので必ずしもテンプレートエンジンが使われなくなったということはないような気はしています。
実際今回EJSを外したのもそういう理由ですし。

**Comment by Fridge0** [comment]
でもさすがにサーバーJSとクライアントHTMLのファイルが一緒になるのはまずくないですか

**Comment by chvmvd** [comment]
別にそういうものだと思いますが。そうしたら、Hello Worldもだめになってしまう...

**Comment by Fridge0** [comment]
> 別にそういうものだと思いますが。そうしたら、Hello Worldもだめになってしまう...

というと？

**Comment by chvmvd** [comment]
Hello WorldとかもHTMLとして送信しているので、それもファイルを分けないといけなくなってしまうということです。

**Comment by Fridge0** [comment]
それはHTMLファイルを読んで送信しているので問題ないです
server.mjs内にHTMLを書くのが問題なのであって
(その点でいうと昔のDOMの課題もCSSがJSファイルにあるので怪しかった)

**Comment by Fridge0** [comment]
あと、https://learn.utcode.net/docs/web-servers/form/ で文字列を送信していると思うのですが、これHTMLとして解釈されてると思うので好ましくないです。(めっちゃ誤魔化してる割にEJSの章でしてた説明がなくなってる)
タグで書くか、HTMLとして送信していることを強調する必要があるかと

**Comment by chvmvd** [comment]
> それはHTMLファイルを読んで送信しているので問題ないです
> 
> server.mjs内にHTMLを書くのが問題なのであって
> 
> (その点でいうと昔のDOMの課題もCSSがJSファイルにあるので怪しかった、練習問題だからいいけど)

JSファイル内に書いてあるのもけっこうあって、それのことですね。

**Comment by chvmvd** [comment]
> あと、https://learn.utcode.net/docs/web-servers/form/ で文字列を送信していると思うのですが、これHTMLとして解釈されてると思うので好ましくないです。(めっちゃ誤魔化してる割にEJSの章でしてたはずの説明がなくなってる)
> 
> タグで書くか、HTMLとして送信していることを強調する必要があるかと

別に誤魔化してもないし、JSファイルに書いても良いと思うのですが...

**Comment by chvmvd** [comment]
まあ、テンプレートエンジンを使う前の段階なのでファイルを頑張って分ける必要はない気がしています...
ちゃんとした開発をするなら、EJSを使うように書いていますし。

**Comment by Fridge0** [comment]
> > あと、https://learn.utcode.net/docs/web-servers/form/ で文字列を送信していると思うのですが、これHTMLとして解釈されてると思うので好ましくないです。(めっちゃ誤魔化してる割にEJSの章でしてたはずの説明がなくなってる)
> > タグで書くか、HTMLとして送信していることを強調する必要があるかと
> 
> 別に誤魔化してもないし、JSファイルに書いても良いと思うのですが...

HTML内に文字列直書きと等価なのでごまかしだと思います。これはまあ文字列送信が最初なのでJS内に書いてもいいと思いますが

**Comment by Fridge0** [comment]
> JSファイル内に書いてあるのもけっこうあって、それのことですね。

JSが万能だからそのケースが多いですが、HTML内にJSやCSSを書くのと同じくらいの罪の重さだと思ってます

**Comment by chvmvd** [comment]
次のミーティングとかで話しましょう。
