### ISSUE TITLE
`node:fs`への移行？

### ISSUE THREAD

**Issue by chvmvd** [ut-code/utcode-learn#588]
ちゃんと調べる。

**Comment by Fridge0** [comment]
Node.js 公式ドキュメントだと
`import * as fs from 'node:fs';`
としてますね

**Comment by chvmvd** [comment]
`import { readFileSync } from 'node:fs';`と書いてますね。cf. https://nodejs.org/api/fs.html#fsreadfilesyncpath-options

**Comment by chvmvd** [comment]
Resolved with #641.
