### ISSUE TITLE
問題が少ない。

### ISSUE THREAD

**Issue by aster-void** [ut-code/utcode-learn#712]

**Comment by aster-void** [comment]
(by @chvmvd )
特に前半問題足りないですよね。

**Comment by aster-void** [comment]
特に前半少ないですよね。

**Comment by chvmvd** [comment]
さすがに、漠然としすぎなIssueではw
もはや作らなくても良いかも。

**Comment by chvmvd** [comment]
> 特に前半少ないですよね。

前半が少ないのは、ある程度は理由がなくもないけど。いずれにしても少ないですね。

**Comment by naka-12** [comment]
これ何をもって解決とするか分からないので閉じていいですか？

**Comment by aster-void** [comment]
#703 で許容できる範囲になったと思いました。
