### ISSUE TITLE
Express の章の訪問者カウンターがコピペで動かない

### ISSUE THREAD

**Issue by aster-void** [ut-code/utcode-learn#764]

**Comment by chvmvd** [comment]
これはコピペを想定していないのでね。

**Comment by aster-void** [comment]
解答例なんだからコピペで動くべきだと思います。 GitHub はまだやってないですし。

**Comment by chvmvd** [comment]
解答例というよりは簡単な解説ですね。GitHubを知っているか否かはここは関係ないですし。

**Comment by aster-void** [comment]
割と難しいらしいので、コピペで動いたといy感触が欲しいと思います。

**Comment by aster-void** [comment]
CodeSandbox はよく分からないページがよく分からない挙動をした結果動いたって感じなので

**Comment by aster-void** [comment]
もしくは、課題をもっと簡単なものに置き換えるか。

**Comment by chvmvd** [comment]
GitHubからコピーする運用にとりあえずするのが良さそうな気はしますね。これについては、GitHubよりももっと分かりやすい方法を探すのが自然かと思います。

**Comment by aster-void** [comment]
GitHub よりもっと分かりやすいのが、 Answer タグ内にコードブロック直置きな感じがします。

**Comment by chvmvd** [comment]
ファイル構造とか示せないですしね。後、すべてを書けるわけではないですし。`package.json`とかもそうですし。

**Comment by naka-12** [comment]
省略するならせめて HTML の章のように省略することを明示すべきだと思います。

**Comment by naka-12** [comment]
ここでは省略していた3行を元に戻す、でいい気がします。

**Comment by aster-void** [comment]
下の app.listen(3000); も省略されてますね。

**Comment by aster-void** [comment]
#771 で修正しました。
