### ISSUE TITLE
「Cookieと認証（発展）」の章の解答を削除する

### ISSUE THREAD

**Issue by chvmvd** [ut-code/utcode-learn#810]
現在の「Cookieと認証（発展）」の演習問題には、解答がありますが、あまり良い解答とはいえません。
解答を作り直すのが理想的ではありますが、「Cookieと認証（発展）」の演習問題自体があまり十分に練られたものとはいえずそもそも問題自体を作り直した方がよいと思われます。しかしながら、「Cookieと認証（発展）」よりも優先して取り組むべきことが多くあります。そのため、一旦は解答を削除することで対応し、今後他のタスクが落ち着き次第「Cookieと認証（発展）」を問題から考え直すこととします。

**Comment by aster-void** [comment]
解決したと思うので閉じます。
